# Generated by Django 5.0.4 on 2024-04-11 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.professor')),
            ],
        ),
    ]
