# Generated by Django 5.0.4 on 2024-04-11 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='professor_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastro.professor'),
        ),
    ]
