# Generated by Django 5.0.4 on 2024-04-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_aluno_professor_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='professor_responsavel',
        ),
    ]
