# Generated by Django 5.0.4 on 2024-04-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_aluno_professor_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='professor_responsavel',
        ),
        migrations.AddField(
            model_name='professor',
            name='materia_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastro.materia'),
        ),
    ]
