# Generated by Django 5.0.4 on 2024-04-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_remove_materia_professor_responsavel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='materia_responsavel',
        ),
        migrations.AddField(
            model_name='materia',
            name='professor_responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastro.professor'),
        ),
    ]
