# Generated by Django 5.0.4 on 2024-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_remove_professor_materia_responsavel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='materias',
            field=models.ManyToManyField(to='cadastro.materia'),
        ),
    ]
