# Generated by Django 5.0.4 on 2024-04-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_aluno_materias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='materias',
            new_name='materias_aluno',
        ),
    ]
