# Generated by Django 5.0.4 on 2024-04-11 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_rename_materias_aluno_materias_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.materia')),
            ],
            options={
                'unique_together': {('aluno', 'materia')},
            },
        ),
    ]
